// connectionType mapping (from backend get_connection_type):
// 0: MySQL, 1: PostgreSQL, 2: Kafka, 3: SQLite, 4: MongoDB,
// 5: OracleDB, 6: MSSQL, 7: Clickhouse, 8: S3

export function getRootNode(node) {
  let tempNode = node;
  while (tempNode.level > 0) {
    tempNode = tempNode.parent;
  }
  return tempNode;
}

export function generateCreateTableSql(
  connectionType,
  tableName = "new_table"
) {
  let mysqlCreateTable = `CREATE TABLE \`${tableName}\` (
    \`id\` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    \`create_time\` DATETIME COMMENT 'Create Time',
    \`name\` VARCHAR(255)
) COMMENT '';`;
  let sqlLiteCreate = `CREATE TABLE \`${tableName}\` (
    \`id\` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    \`content\` TEXT
);`;
  let oracleCreateTable = `CREATE TABLE "${tableName}" (
    "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP,
    "NAME" VARCHAR2(255)
);`;
  let postgresqlCreateTable = `CREATE TABLE "${tableName}" (
    "id" SERIAL PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT NOW(),
    "name" VARCHAR(255)
);`;
  let mssqlCreateTable = `CREATE TABLE [${tableName}] (
    [id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    [created_at] DATETIME DEFAULT GETDATE(),
    [name] NVARCHAR(255)
);`;
  let clickhouseCreateTable = `CREATE TABLE ${tableName} (
    id UInt32,
    created_at DateTime DEFAULT now(),
    name String
) ENGINE = MergeTree()
ORDER BY id;`;

  if (connectionType === 0) {
    return mysqlCreateTable;
  } else if (connectionType === 3) {
    return sqlLiteCreate;
  } else if (connectionType === 5) {
    return oracleCreateTable;
  } else if (connectionType === 1) {
    return postgresqlCreateTable;
  } else if (connectionType === 6) {
    return mssqlCreateTable;
  } else if (connectionType === 7) {
    return clickhouseCreateTable;
  }
  return `/* Warning: Unknown connection type (${connectionType}), using generic CREATE TABLE for ${tableName} */\nCREATE TABLE ${tableName} (\n    id INT PRIMARY KEY,\n    name VARCHAR(255)\n);`;
}

export function generateCreateColumnSql(
  connectionType,
  tableName = "your_table"
) {
  let mysqlCreateColumn = `ALTER TABLE \`${tableName}\`
    ADD COLUMN \`new_column_name\` [TYPE] COMMENT '' AFTER \`existing_column\`;`;
  let sqlLiteCreateColumn = `
ALTER TABLE \`${tableName}\`
    ADD COLUMN \`new_column_name\` [TYPE];`;
  let oracleCreateColumn = `ALTER TABLE "${tableName}"
    ADD "NEW_COLUMN_NAME" [TYPE];`;
  let postgresqlCreateColumn = `ALTER TABLE "${tableName}"
    ADD COLUMN "new_column_name" [TYPE];`;
  let mssqlCreateColumn = `ALTER TABLE [${tableName}]
    ADD [new_column_name] [TYPE] NULL;`;
  let clickhouseCreateColumn = `ALTER TABLE ${tableName}
    ADD COLUMN new_column_name [TYPE];`;

  if (connectionType === 0) {
    return mysqlCreateColumn;
  } else if (connectionType === 3) {
    return sqlLiteCreateColumn;
  } else if (connectionType === 5) {
    return oracleCreateColumn;
  } else if (connectionType === 1) {
    return postgresqlCreateColumn;
  } else if (connectionType === 6) {
    return mssqlCreateColumn;
  } else if (connectionType === 7) {
    return clickhouseCreateColumn;
  }
  return `/* Warning: Unknown connection type (${connectionType}), using generic ALTER TABLE ADD COLUMN for ${tableName} */\nALTER TABLE ${tableName} ADD COLUMN new_column_name [TYPE];`;
}

export function generateCreateIndexSql(
  connectionType,
  tableName = "your_table"
) {
  let mysqlCreateIndex = `ALTER TABLE \`${tableName}\` ADD KEY \`idx_${tableName}_column\` (\`column_name_to_index\`);`;
  let sqlLiteCreateIndex = `CREATE INDEX \`idx_${tableName}_column\` ON \`${tableName}\` (\`column_name_to_index\`);`;
  let oracleCreateIndex = `CREATE INDEX "IDX_${tableName.toUpperCase()}_COL" ON "${tableName.toUpperCase()}" ("COLUMN_NAME_TO_INDEX");`;
  let postgresqlCreateIndex = `CREATE INDEX "idx_${tableName}_column" ON "${tableName}" ("column_name_to_index");`;
  let mssqlCreateIndex = `CREATE INDEX [idx_${tableName}_column] ON [${tableName}] ([column_name_to_index]);`;
  let clickhouseCreateIndex = `CREATE INDEX idx_${tableName}_column column_name_to_index TYPE minmax GRANULARITY 1;`;

  if (connectionType === 0) {
    return mysqlCreateIndex;
  } else if (connectionType === 3) {
    return sqlLiteCreateIndex;
  } else if (connectionType === 5) {
    return oracleCreateIndex;
  } else if (connectionType === 1) {
    return postgresqlCreateIndex;
  } else if (connectionType === 6) {
    return mssqlCreateIndex;
  } else if (connectionType === 7) {
    return clickhouseCreateIndex;
  }
  return `/* Warning: Unknown connection type (${connectionType}), using generic CREATE INDEX for ${tableName} */\nCREATE INDEX idx_${tableName}_column ON ${tableName} (column_name_to_index);`;
}

// The following functions are provided in your context but not directly used by the current request.
// Keeping them as is, but commenting out their internal logic that relies on `getRootNode`
// which might not work with the current node structure without further adaptation.
export function getAlterColumnSql(node, tableName, column, description) {
  let mysqlAlterColumn = `ALTER TABLE \`${tableName}\`
	CHANGE \`${column}\` \`${column}\` ${description} DEFAULT NULL ;`;
  return `/* getAlterColumnSql: Feature not fully implemented for dynamic connection types. */\n${mysqlAlterColumn}`;
}

export function getCreateColumnAfterAnotherSql(node, tableName, column) {
  let mysqlCreateColumn = `ALTER TABLE ${tableName}
    ADD COLUMN  [type] COMMENT '' AFTER \`${column}\`;`;
  let sqlLiteCreateColumn = `
ALTER TABLE ${tableName}
    ADD COLUMN  [type];`;
  return `/* getCreateColumnAfterAnotherSql: Feature not fully implemented for dynamic connection types. */\n${mysqlCreateColumn}`;
}

export function getCreateIndexForColumn(node, tableName) {
  console.log(node, tableName);
  return `/* getCreateIndexForColumn: Feature not fully implemented for dynamic connection types. */`;
}
