export function getRootNode(node) {
  let tempNode = node;
  while (tempNode.level > 0) {
    tempNode = tempNode.parent;
  }
  return tempNode;
}

// Renamed and adapted from user's getCreateTableSql
// connectionType: 1 for MySQL, 3 for SQLite, 2 for Oracle
export function generateCreateTableSql(
  connectionType,
  tableName = "new_table"
) {
  let mysqlCreateTable = `CREATE TABLE \`${tableName}\` (
    \`id\` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    \`create_time\` DATETIME COMMENT 'Create Time',
    \`name\` VARCHAR(255)
) COMMENT '';`;
  let sqlLiteCreate = `CREATE TABLE \`${tableName}\` (
    \`id\` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    \`content\` TEXT
);`;
  // Oracle example (not explicitly provided by user, but good to have a placeholder)
  let oracleCreateTable = `CREATE TABLE "${tableName}" (
    "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    "CREATED_AT" TIMESTAMP DEFAULT SYSTIMESTAMP,
    "NAME" VARCHAR2(255)
);`;

  if (connectionType === 1) {
    // Corresponds to user's old connectionType 0
    return mysqlCreateTable;
  } else if (connectionType === 3) {
    return sqlLiteCreate;
  } else if (connectionType === 2) {
    // Oracle
    return oracleCreateTable;
  }
  return `/* Warning: Unknown connection type (${connectionType}), using generic CREATE TABLE for ${tableName} */\nCREATE TABLE \`${tableName}\` (\n    id INT PRIMARY KEY,\n    name VARCHAR(255)\n);`;
}

// Renamed and adapted from user's getCreateColumnSql
export function generateCreateColumnSql(
  connectionType,
  tableName = "your_table"
) {
  let mysqlCreateColumn = `ALTER TABLE \`${tableName}\`
    ADD COLUMN \`new_column_name\` [TYPE] COMMENT '' AFTER \`existing_column\`;`; // Added placeholder
  let sqlLiteCreateColumn = `
ALTER TABLE \`${tableName}\`
    ADD COLUMN \`new_column_name\` [TYPE];`; // Added placeholder
  let oracleCreateColumn = `ALTER TABLE "${tableName}"
    ADD "NEW_COLUMN_NAME" [TYPE];`;

  if (connectionType === 1) {
    // Corresponds to user's old connectionType 0
    return mysqlCreateColumn;
  } else if (connectionType === 3) {
    return sqlLiteCreateColumn;
  } else if (connectionType === 2) {
    // Oracle
    return oracleCreateColumn;
  }
  return `/* Warning: Unknown connection type (${connectionType}), using generic ALTER TABLE ADD COLUMN for ${tableName} */\nALTER TABLE \`${tableName}\` ADD COLUMN \`new_column_name\` [TYPE];`;
}

// Renamed and adapted from user's getCreateIndexSql
export function generateCreateIndexSql(
  connectionType,
  tableName = "your_table"
) {
  let mysqlCreateIndex = `ALTER TABLE \`${tableName}\` ADD KEY \`idx_${tableName}_column\` (\`column_name_to_index\`);`; // Added index name and column name placeholder
  let sqlLiteCreateIndex = `CREATE INDEX \`idx_${tableName}_column\` ON \`${tableName}\` (\`column_name_to_index\`);`; // Added index name and column name placeholder
  let oracleCreateIndex = `CREATE INDEX "IDX_${tableName.toUpperCase()}_COL" ON "${tableName.toUpperCase()}" ("COLUMN_NAME_TO_INDEX");`;

  if (connectionType === 1) {
    // Corresponds to user's old connectionType 0
    return mysqlCreateIndex;
  } else if (connectionType === 3) {
    return sqlLiteCreateIndex;
  } else if (connectionType === 2) {
    // Oracle
    return oracleCreateIndex;
  }
  return `/* Warning: Unknown connection type (${connectionType}), using generic CREATE INDEX for ${tableName} */\nCREATE INDEX \`idx_${tableName}_column\` ON \`${tableName}\` (\`column_name_to_index\`);`;
}

// The following functions are provided in your context but not directly used by the current request.
// Keeping them as is, but commenting out their internal logic that relies on `getRootNode`
// which might not work with the current node structure without further adaptation.
export function getAlterColumnSql(node, tableName, column, description) {
  let mysqlAlterColumn = `ALTER TABLE \`${tableName}\`
	CHANGE \`${column}\` \`${column}\` ${description} DEFAULT NULL ;`;
  // let rootNode = getRootNode(node)
  // if (rootNode.data.connectionType === 0) {
  //   return mysqlAlterColumn
  // } else return null
  return `/* getAlterColumnSql: Feature not fully implemented for dynamic connection types. */\n${mysqlAlterColumn}`;
}

export function getCreateColumnAfterAnotherSql(node, tableName, column) {
  let mysqlCreateColumn = `ALTER TABLE ${tableName}
    ADD COLUMN  [type] COMMENT '' AFTER \`${column}\`;`;
  let sqlLiteCreateColumn = `
ALTER TABLE ${tableName}
    ADD COLUMN  [type];`;
  // let rootNode = getRootNode(node)
  // if (rootNode.data.connectionType === 0) {
  //   return mysqlCreateColumn
  // } else if (rootNode.data.connectionType === 3) {
  //   return sqlLiteCreateColumn
  // }
  return `/* getCreateColumnAfterAnotherSql: Feature not fully implemented for dynamic connection types. */\n${mysqlCreateColumn}`;
}

export function getCreateIndexForColumn(node, tableName) {
  console.log(node, tableName);
  // let mysqlCreateColumn = `ALTER TABLE ${tableName} ADD key (\`${node.data.name}\`)`
  // let sqlLiteCreateColumn = `CREATE INDEX ${tableName}_ ON ${tableName}`
  // let rootNode = getRootNode(node)
  // if (rootNode.data.connectionType === 0) {
  //   return mysqlCreateColumn
  // } else if (rootNode.data.connectionType === 3) {
  //   return sqlLiteCreateColumn
  // }
  return `/* getCreateIndexForColumn: Feature not fully implemented for dynamic connection types. */`;
}
